<?php

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use app\actions\sample\book\BookMenu;
use app\models\sample\Book;
use app\widgets\SplitDropdown;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $searchModel app\actions\sample\book\PersonSearch */

$this->title = $searchModel->modelLabel(true);
$this->params['breadcrumbs'][] = Yii::t('sample', 'Sample');
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="giiant-crud book-index">

    <div class="clearfix crud-navigation" style="padding-top: 30px;">
        <div class="pull-left">
            <h1 style="margin-top: 0;">
                <?= $searchModel->modelLabel(TRUE) ?>
                <small>
                    <?= Yii::t('cruds', 'List') ?>
                </small>
            </h1>
        </div>
        <div class="pull-right">
            <div>
                <?=
                SplitDropdown::widget([
                    'label' => BookMenu::iconFor('create').'&nbsp; '.BookMenu::labelFor('create'),
                    'encodeLabel' => FALSE,
                    'buttonAction' => 'create',
                    'options' => [
                        'class' => 'btn btn-primary',
                    ],
                    'dropdownActions' => [
                        'create',
                        [
                            'deleted',
                            'archive',
                        ],
                    ],
                    'dropdownButtons' => BookMenu::dropdownButtons(),
                    'urlCreator' => function($action, $model) {
                        return BookMenu::createUrlFor($action, $model);
                    },
                ]);
                ?>
            </div>
        </div>
    </div>

    <?php //= $this->render('_search', ['model' => $searchModel]); ?>

    <hr style="margin-top: 0;" />

    <?php
    \yii\widgets\Pjax::begin([
        'id' => 'pjax-main',
        'enableReplaceState' => false,
        'linkSelector' => '#pjax-main ul.pagination a, th a',
        'clientOptions' => [
            'pjax:success' => 'function(){alert("yo")}',
        ],
    ]);
    ?>

    <div>
        <?=
        \kartik\grid\GridView::widget([
            'dataProvider' => $dataProvider,
            'pager' => [
                'class' => \yii\widgets\LinkPager::class,
                'firstPageLabel' => Yii::t('cruds', 'First'),
                'lastPageLabel' => Yii::t('cruds', 'Last'),
            ],
            'filterModel' => $searchModel,
            'responsive' => false,
            'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
            'headerRowOptions' => ['class' => 'x'],
            'columns' => [
                [
                    'class' => \kartik\grid\SerialColumn::class,
                ],
                'title:ntext',
                'description:ntext',
                // generated by app\generators\crud\providers\RelationProvider::columnFormat
                [
                    'attribute' => 'author_id',
                    'format' => 'html',
                    'value' => function ($model) {
                        /* @var $model \app\models\sample\Book */
                        return ArrayHelper::getValue($model, 'author.name');
                    },
                ],
                // generated by app\generators\crud\providers\RelationProvider::columnFormat
                [
                    'attribute' => 'editor_id',
                    'format' => 'html',
                    'value' => function ($model) {
                        /* @var $model \app\models\sample\Book */
                        return ArrayHelper::getValue($model, 'editor.name');
                    },
                ],
                [
                    'attribute' => 'released_date',
                    'format' => [
                        'date',
                        'format' => 'eee, d MMM Y',
                    ],
                    'filter' => $searchModel->releasedSearch->filterWidget(),
                ],
                [
                    'class' => \app\components\ActionColumn::class,
                    'contentRenderer' => function($model, $key, $index) {
                        return SplitDropdown::widget([
                                'model' => $model,
                                'label' => BookMenu::iconFor('view').' '.BookMenu::labelFor('view'),
                                'buttonAction' => 'view',
                                'dropdownActions' => [
                                    'view',
                                    'update',
                                    [
                                        'delete',
                                    ],
                                ],
                                'dropdownButtons' => BookMenu::dropdownButtons(),
                                'urlCreator' => function($action, $model) {
                                    return BookMenu::createUrlFor($action, $model);
                                },
                        ]);
                    },
                ],
            ],
        ]);
        ?>
    </div>

    <?php \yii\widgets\Pjax::end() ?>

</div>
