<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cities' => 'Kota',
    'City Archives' => 'Arsip Kota',
    'Country Archives' => 'Arsip Negara',
    'Deleted City' => 'Kota Terhapus',
    'Deleted Country' => 'Negara Terhapus',
    'Deleted District' => 'Kecamatan Terhapus',
    'Deleted Region' => 'Provinsi Terhapus',
    'Deleted Subdistrict' => 'Kelurahan Terhapus',
    'Deleted Type' => 'Tipe Terhapus',
    'District Archives' => 'Arsip Kecamatan',
    'Districts' => 'Kecamatan',
    'Geo Address' => 'Alamat Geografis',
    'New City' => 'Kota Baru',
    'New Country' => 'Negara Baru',
    'New District' => 'Kecamatan Baru',
    'New Region' => 'Provinsi Baru',
    'New Subdistrict' => 'Kelurahan Baru',
    'New Type' => 'Tipe Baru',
    'Region Archives' => 'Arsip Provinsi',
    'Regions' => 'Provinsi',
    'Subdistrict Archives' => 'Arsip Kelurahan',
    'Subdistricts' => 'Kelurahan',
    'Type Archives' => 'Arsip Tipe',
    'View City' => 'Lihat Kota',
    'View Country' => 'Lihat Negara',
    'View District' => 'Lihat Kecamatan',
    'View Region' => 'Lihat Provinsi',
    'View Subdistrict' => 'Lihat Kelurahan',
    'View Type' => 'Lihat Tip',
];
