<?php

use yii\bootstrap\ButtonDropdown;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use app\actions\geographical_hierarchy\city\CityMenu;
use app\components\Tabs;
use app\models\geographical_hierarchy\City;
use app\widgets\SplitDropdown;

/* @var $this yii\web\View  */
/* @var $model City  */

$this->title = Yii::t('geographical_hierarchy','View City').' #'.$model->id;
$this->params['breadcrumbs'][] = Yii::t('geographical_hierarchy', 'Geographical Hierarchy');
$this->params['breadcrumbs'][] = ['label' => $model->modelLabel(true), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string) $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('cruds', 'View');
?>
<div class="giiant-crud city-view">

    <div class="clearfix crud-navigation" style="padding-top: 30px;">
        <div class="pull-left">
            <h1 style="margin-top: 0;">
                <?= $model->modelLabel() ?>
                <small>
                    #<?= $model->id ?>
                </small>
            </h1>
        </div>

        <!-- menu buttons -->
        <div class='pull-right'>
            <div>
                <?=
                SplitDropdown::widget([
                    'model' => $model,
                    'label' => CityMenu::iconFor('create').'&nbsp; '.CityMenu::labelFor('create'),
                    'encodeLabel' => FALSE,
                    'buttonAction' => 'update',
                    'dropdownActions' => [
                        'view',
                        [
                            'delete',
                        ],
                    ],
                    'dropdownButtons' => CityMenu::dropdownButtons(),
                    'urlCreator' => function($action, $model) {
                        return CityMenu::createUrlFor($action, $model);
                    },
                ]);
                ?>
            </div>
        </div>

    </div>

    <hr/>

    
    <?= 
    DetailView::widget([
        'model' => $model,
        'attributes' => [
            'name',
            // generated by app\generators\crud\providers\RelationProvider::attributeFormat
            [
                'attribute' => 'type_id',
                'format' => 'html',
                'value' => ArrayHelper::getValue($model, 'type.name', '<span class="label label-warning">?</span>'),
            ],
            // generated by app\generators\crud\providers\RelationProvider::attributeFormat
            [
                'attribute' => 'country_id',
                'format' => 'html',
                'value' => ArrayHelper::getValue($model, 'country.name', '<span class="label label-warning">?</span>'),
            ],
            // generated by app\generators\crud\providers\RelationProvider::attributeFormat
            [
                'attribute' => 'region_id',
                'format' => 'html',
                'value' => ArrayHelper::getValue($model, 'region.name', '<span class="label label-warning">?</span>'),
            ],
            'reg_number',
        ],
    ]);
    ?>

    
    <hr/>
    <br/>
    <h3><?= Yii::t('geographical_hierarchy', 'Districts') ?></h3>
    <div class="table-responsive">
        <?=
        \kartik\grid\GridView::widget([
            'layout' => '{summary}{pager}<br/>{items}{pager}',
            'dataProvider' => new \yii\data\ActiveDataProvider([
                'query' => $model->getDistricts(),
                'pagination' => [
                    'pageSize' => 20,
                    'pageParam' => 'page-districts',
                ],
            ]),
            'columns' => [
                [
                    'class' => \kartik\grid\SerialColumn::class,
                ],
                'name',
                'reg_number',
            ],
        ]);
        ?>
    </div>
    <br/>
    <hr/>

</div>
