<?php

use yii\bootstrap\ButtonDropdown;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use cornernote\returnurl\ReturnUrl;
use app\lib\geo_address\district\DistrictAC;
use app\models\geo_address\District;

/* @var $this yii\web\View  */
/* @var $model District  */

$this->title = Yii::t('app/geo_address/texts','View District').' #'.$model->id;
$this->params['breadcrumbs'][] = Yii::t('app/geo_address/texts', 'Geo Address');
$this->params['breadcrumbs'][] = ['label' => $model->modelLabel(true), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string) $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('cruds', 'View');
?>
<div class="app-crud district-view">

    <div class="clearfix crud-navigation" style="padding-top: 30px;">
        <div class="pull-left">
            <h1 style="margin-top: 0;">
                <?= $model->modelLabel() ?>
                <small>
                    #<?= $model->id ?>
                </small>
            </h1>
        </div>

        <!-- menu buttons -->
        <div class="pull-right">
            <div>
                <?=
                ButtonDropdown::widget([
                    'label' => 'Menu',
                    'options' => [
                        'class' => 'btn btn-primary',
                    ],
                    'dropdown' => [
                        'items' => [
                            [
                                'label' => '<span class="glyphicon glyphicon-pencil"></span> '.Yii::t('cruds', "Edit"),
                                'encode' => FALSE,
                                'url' => [
                                    'update',
                                    'id' => $model->id,
                                    'ru' => ReturnUrl::getToken(),
                                ],
                                'visible' => DistrictAC::canUpdate(),
                            ],
                            //'<li role="presentation" class="divider"></li>',
                        ],
                    ],
                ])
                ?>
            </div>
        </div>

    </div>

    <hr/>

    
    <?=
    DetailView::widget([
        'model' => $model,
        'attributes' => [
            'name',
            // generated by app\generators\crud\providers\RelationProvider::attributeFormat
            [
                'attribute' => 'type_id',
                'format' => 'html',
                'value' => ArrayHelper::getValue($model, 'type.name', '<span class="label label-warning">?</span>'),
            ],
            // generated by app\generators\crud\providers\RelationProvider::attributeFormat
            [
                'attribute' => 'city_id',
                'format' => 'html',
                'value' => ArrayHelper::getValue($model, 'city.name', '<span class="label label-warning">?</span>'),
            ],
            'reg_number',
        ],
    ]);
    ?>

    
    <hr/>
    <br/>
    <h3><?= Yii::t('app/geo_address/texts', 'Subdistricts') ?></h3>
    <div class="table-responsive">
        <?=
        \kartik\grid\GridView::widget([
            'layout' => '{summary}{pager}<br/>{items}{pager}',
            'dataProvider' => new \yii\data\ActiveDataProvider([
                'query' => $model->getSubdistricts(),
                'pagination' => [
                    'pageSize' => 20,
                    'pageParam' => 'page-subdistricts',
                ],
            ]),
            'columns' => [
                [
                    'class' => \kartik\grid\SerialColumn::class,
                ],
                'name',
                // generated by app\generators\crud\providers\RelationProvider::columnFormat
                [
                    'attribute' => 'type_id',
                    'format' => 'html',
                    'value' => function ($model) {
                        /* @var $model \app\models\geo_address\Subdistrict */
                        return ArrayHelper::getValue($model, 'type.name');
                    },
                ],
                // generated by app\generators\crud\providers\RelationProvider::columnFormat
                [
                    'attribute' => 'district_id',
                    'format' => 'html',
                    'value' => function ($model) {
                        /* @var $model \app\models\geo_address\Subdistrict */
                        return ArrayHelper::getValue($model, 'district.name');
                    },
                ],
                'reg_number',
            ],
        ]);
        ?>
    </div>
    <br/>
    <hr/>

    <div class="clearfix">
        <!-- danger menu buttons -->
        <div class='pull-right'>
            <div>
                <?php
                if (DistrictAC::canDelete()) {
                    $label = '<span class="glyphicon glyphicon-trash"></span> '.Yii::t('cruds', 'Delete');
                    $options = [
                        'class' => 'btn btn-danger',
                        'title' => Yii::t('cruds', 'Delete'),
                        'aria-label' => Yii::t('cruds', 'Delete'),
                        'data-confirm' => Yii::t('cruds', 'Are you sure to delete this item?'),
                        'data-method' => 'post',
                        'data-pjax' => FALSE,
                    ];
                    $url = [
                        'delete',
                        'id' => $model->id,
                        'ru' => ReturnUrl::urlToToken(Url::to(['index'])),
                    ];
                    echo Html::a($label, $url, $options);
                }
                ?>
            </div>
        </div>
    </div>


</div>
